"""
Evolution module for Glassbox.

This module contains the evolutionary training algorithms for Operation-Based Neural Networks.
"""

from .evolution import (
    EvolutionaryONNTrainer,
    Individual,
    StructureConfidenceTracker,
    ablate_and_select_terms,
    adaptive_coefficient_pruning,
    anneal_entropy_weight,
    anneal_tau,
    calculate_complexity,
    check_structure_quality,
    coefficient_sparsity_loss,
    compute_param_sensitivity,
    detect_dominant_frequency,
    finalize_model_coefficients,
    intensive_coefficient_refinement,
    mutate_operations,
    mutate_operations_gradient_informed,
    mutate_operations_lamarckian,
    progressive_round_loss,
    prune_small_coefficients,
    quick_refine_internal,
    random,
    random_operation_init,
    refine_constants,
    seed_omega_from_fft,
    seed_population_from_classifier,
    set_model_tau,
    torch,
    train_onn_evolutionary,
    train_onn_hybrid,
)

__all__ = [
    "EvolutionaryONNTrainer",
    "Individual",
    "StructureConfidenceTracker",
    "ablate_and_select_terms",
    "adaptive_coefficient_pruning",
    "anneal_entropy_weight",
    "anneal_tau",
    "calculate_complexity",
    "check_structure_quality",
    "coefficient_sparsity_loss",
    "compute_param_sensitivity",
    "detect_dominant_frequency",
    "finalize_model_coefficients",
    "intensive_coefficient_refinement",
    "mutate_operations",
    "mutate_operations_gradient_informed",
    "mutate_operations_lamarckian",
    "progressive_round_loss",
    "prune_small_coefficients",
    "quick_refine_internal",
    "random",
    "random_operation_init",
    "refine_constants",
    "seed_omega_from_fft",
    "seed_population_from_classifier",
    "set_model_tau",
    "torch",
    "train_onn_evolutionary",
    "train_onn_hybrid",
]
